name: XeraVanish
version: 1.0.0
main: me.alexprogrammerde.XeraVanish.XeraVanish
author: AlexProgrammerDE
description: A anarchy server oriented vanishing plugin.
commands:
  vanish:
    description: Command to vanish and unvanish yourself
permissions:
  xeravanish.vanish:
    description: Allows you to vanish and unvanish yourself