name: CustomStats
version: ${project.version}
main: me.stats.XeraVanish.XeraVanish
author: 7man7LMYT
description: A plugin that adds /stats.
commands:
  stats:
    description: Command to vanish and unvanish yourself.
    permission: customstats.stats
    permission-message: Unknown command.
permissions:
  customstats.stats:
    description: Allows the use of /stats.
